package es.example.spark.streaming

import es.example.spark.SparkHelper
import org.apache.spark.storage.StorageLevel
import org.apache.spark.streaming.{Seconds, StreamingContext}


/**
  * Ejemplo operaciones con ventanas de tiempo
  *
  * Uso: Main <hostname> <port> <hostname2> <port2>
  * <hostname> y <port> describen el servidor TCP en el que Spark Streaming estara esperando por datos
  *
  * Para ejecutar, primero ejecute un Netcat server
  *    `$ nc -lk 9999`
  * y luego conecte el ejemplo
  */
object WindowStreaming {
  def main(args: Array[String]): Unit = {
    if (args.length < 2) {
      System.err.println("uso: WindowStreaming <host> <puerto>")
      System.exit(1)
    }

    // Create the context with a 1 second batch size
    val sparkSession = SparkHelper.getAndConfigureSparkSession(Some("Spark Literature"), master = Some("local[2]"))
    sparkSession.sparkContext.setLogLevel("ERROR")
    val ssc = new StreamingContext(sparkSession.sparkContext, Seconds(5))

    // Create a socket stream on target ip:port and count the
    // words in input stream of \n delimited text (eg. generated by 'nc')
    // Note that no duplication in storage level only for running locally.
    // Replication necessary in distributed scenario for fault tolerance.
    val lines = ssc.socketTextStream(args(0), args(1).toInt, StorageLevel.MEMORY_AND_DISK_SER)
    val allLines = lines.window(Seconds(10), Seconds(5))

    val words = allLines.flatMap(_.split(" "))
    val wordCounts = words.map(x => (x, 1)).reduceByKey(_ + _)
    wordCounts.print()
    ssc.start()
    ssc.awaitTermination()
  }
}
